# Generated by Django 5.1.1 on 2025-07-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='phone',
        ),
    ]
