# Generated by Django 5.1.1 on 2025-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Closed', 'Closed')], default='Active', help_text='Current status of the job posting', max_length=50),
        ),
    ]
