# Generated by Django 5.1.1 on 2025-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_posting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='documents_needed',
            field=models.TextField(blank=True, help_text='List of documents required from applicants (e.g., resume, cover letter, portfolio)', null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='end_date',
            field=models.DateField(blank=True, help_text='Estimated end date of the job (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Indicates if the posting offers payment.'),
        ),
        migrations.AddField(
            model_name='posting',
            name='location',
            field=models.CharField(blank=True, help_text='Geographic location of the job', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='payment_details',
            field=models.TextField(blank=True, help_text='Details about payment (e.g., salary range, hourly rate).', null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='start_date',
            field=models.DateField(blank=True, help_text='Estimated start date of the job', null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional information about the job.', null=True),
        ),
    ]
