# Generated by Django 5.1.1 on 2025-07-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_posting_documents_needed_posting_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='posting',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('UGX', 'Ugandan Shilling')], help_text='Currency of the payment.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value for the payment rate.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='wage_type',
            field=models.CharField(choices=[('HOURLY', 'Per Hour'), ('COMMISSION', 'Per Commission'), ('PROJECT', 'Per Project'), ('SALARY', 'Salary'), ('UNPAID', 'Unpaid')], default='UNPAID', help_text='Type of wage offered.', max_length=20),
        ),
        migrations.AlterField(
            model_name='posting',
            name='documents_needed',
            field=models.CharField(choices=[('Resume/CV', 'Resume or CV'), ('Cover Letter', 'Cover Letter'), ('Portfolio/work samples', 'Portfolio or work samples'), ('Academic Transcript', 'Academic Transcript'), ('Letter of Recommendation', 'Letter of recommendation'), ('Proof of enrollment', 'Proof of enrollment'), ('NONE', 'None Required')], default='RESUME', help_text='Documents required from applicants.', max_length=50),
        ),
    ]
