# Generated by Django 5.1.1 on 2025-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_posting_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='documents_needed',
            field=models.JSONField(blank=True, default=list, help_text="A list of documents required from applicants (e.g., ['Resume', 'Cover Letter'])."),
        ),
    ]
