# Generated by Django 5.1.1 on 2025-07-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Unopened', 'Unopened'), ('Pending', 'Pending'), ('Denied', 'Denied'), ('Interview Scheduled', 'Interview Scheduled'), ('Active', 'Active'), ('Completed', 'Completed')], default='Unopened', max_length=20),
        ),
    ]
