# Generated by Django 5.1.1 on 2025-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback/comments from the representative', null=True),
        ),
    ]
