# Generated by Django 5.1.1 on 2025-07-29 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_application_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='location',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='interview',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the interview', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the interview'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time of the interview'),
        ),
        migrations.AddField(
            model_name='interview',
            name='location_type',
            field=models.CharField(choices=[('physical', 'Physical Location'), ('online', 'Online Meeting')], default='online', help_text='Type of interview location', max_length=10),
        ),
        migrations.AddField(
            model_name='interview',
            name='physical_address',
            field=models.TextField(blank=True, help_text='Physical address for in-person interview', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Unopened', 'Unopened'), ('Under Review', 'Under Review'), ('Decision Pending', 'Decision Pending'), ('Denied', 'Denied'), ('Interview Scheduled', 'Interview Scheduled'), ('Active', 'Active'), ('Completed', 'Completed')], default='Unopened', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link for online interview', null=True),
        ),
    ]
