# Generated by Django 5.1.1 on 2025-07-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_interview_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
