# Generated by Django 5.1.1 on 2025-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='active_end_date',
            field=models.DateField(blank=True, help_text='End date for active internship', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='active_start_date',
            field=models.DateField(blank=True, help_text='Start date for active internship', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='supervisor',
            field=models.CharField(blank=True, help_text='Supervisor assigned for active internships', max_length=255, null=True),
        ),
    ]
