# Generated by Django 5.1.1 on 2025-07-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_application_active_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text="Supervisor assigned for active internships (must be a representative from the posting's company)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_applications', to='api.representative'),
        ),
    ]
