# Generated by Django 5.1.1 on 2025-08-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_application_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='bio',
        ),
    ]
