# Generated by Django 5.1.1 on 2025-08-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_applicant_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadmin',
            name='phone',
        ),
    ]
