# Generated by Django 5.1.1 on 2024-11-07 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('imgUrl', models.CharField(max_length=2083)),
                ('price', models.FloatField()),
                ('isActive', models.BooleanField(default=True)),
                ('auctioneer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_as_auctioneer', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.category')),
            ],
        ),
    ]
