# Generated by Django 5.1.1 on 2025-02-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'receivingFollowUser')},
        ),
    ]
