# Generated by Django 5.1.1 on 2025-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_follow_unique_together_follow_unique_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=400),
        ),
    ]
